### PR TITLE
Add extensions for Decodable

### PR DESCRIPTION
**Pull request by hamtiko**
Add response methods for Decodable

### CODE REVIEW

**Comment by choule99** [comment]
I tested it, and it works perfectly. Here is to hoping that this get merged ASAP

**Comment by gianfigueroa** [comment]
I need it

**Comment by choule99** [comment]
@gianfigueroa If you are using cocoapods, you can easily use it now with the following line in your Podfile:

`pod 'RxAlamofire', :git => 'git@github.com:hamtiko/RxAlamofire.git', :branch => 'master'`

**Comment by gianfigueroa** [comment]
I use swift package manager, Can I?

**Comment by hamtiko** [comment]
> I use swift package manager, Can I?

@gianfigueroa Yes you can, If you are using `Package.swift` file just add following:

```swift
.package(url: "https://github.com/hamtiko/RxAlamofire.git", .branch("master"))
```

If you are using Xcode interface, just add package like it show in below screenshot:

image

**Comment by rynecheow** [comment]
Hey there @hamtiko, thank you for your PR! Would you be able to add a few unit tests around the new functions that you have added in?

**Comment by hamtiko** [comment]
@rynecheow I would be happy just I have no idea how to do that. New functions are only wrappers for existing Alamofire functions. 

Is there any best practice to have unit tests for wrapper functions?

Thanks.

**Comment by rynecheow** [comment]
@hamtiko They can be unit tested through RxBlocking - you can refer to the existing test cases too. It is a shame that most of the functions are not given a proper unit test and we are looking at getting this better maintained in the future too. I'll probably go ahead and merge this first and you could follow up with a PR on the tests later.

**Pull request merged**
