### PR TITLE
Xcode 9.0 & Swift 4.0 Support

### LINKED ISSUE #87: Swift 4
When can we expect Swift 4 support?

Thank you!

### PR DESCRIPTION
**Pull request by gaplo917**
Resolve #87

### CODE REVIEW

**Comment by gaplo917** [comment]
If you want to use this PR in your project. You may try the following

Cocoapods
```pod 'RxAlamofire', :git => 'https://github.com/gaplo917/RxAlamofire.git', :tag => '4.0.0' ```

Carthage
```github "gaplo917/RxAlamofire" "master"```

**Comment by orta** [comment]
Hrm, a bit hard to review at a whopping 404 files changed, but I guess that's just a trade-off with having to support all possible tools.

**Comment by orta** [comment]
I'm not comfortable making the release though - that's still on @sergdort or @kzaher

**Comment by abdullahnkhan** [comment]
any ETA on the release

**Comment by sergdort** [comment]
Gonna try to find some time to release it this week

**Comment by sergdort** [comment]
@abdullahnkhan I've pushed the spec '4.0.0-rc.0'

**Comment by abdullahnkhan** [comment]
@sergdort Many thanks!

**Pull request merged**
