### PR TITLE
Adding some extensions for upload

### PR DESCRIPTION
**Pull request by hamtiko**
Extensions added:
upload(_ file:to:method:headers:) -> Observable<UploadRequest>
upload(_ file:to:method:headers:) -> Observable<RxProgress>
upload(_ data:to:method:headers:) -> Observable<UploadRequest>
upload(_ data:to:method:headers:) -> Observable<RxProgress>
upload(_ stream:to:method:headers:) -> Observable<UploadRequest>
upload(_ stream:to:method:headers:) -> Observable<RxProgress>
upload(multipartFormData:urlRequest:) -> Observable<UploadRequest>
upload(multipartFormData:to:method:headers:) -> Observable<UploadRequest>
upload(multipartFormData:to:method:headers:) -> Observable<RxProgress>

### CODE REVIEW

**Comment by hamtiko** [comment]
@rynecheow Do you have any idea how I can add tests for new extensions? 

I found that `OHHTTPStubs` can't help for simulating upload requests according to known limitations (https://github.com/AliSoftware/OHHTTPStubs#known-limitations).

**Comment by rynecheow** [comment]
Hey @hamtiko Are you able to fix the lint issues by running the cleanup script?

**Comment by hamtiko** [comment]
@rynecheow done. it seems we need to update `cleanup.sh` script as it is referring to `setup.sh` script which is missing.

**Comment by rynecheow** [comment]
Hey @hamtiko Is this PR still a WIP?

**Comment by hamtiko** [comment]
@rynecheow I am trying to find a way to add tests for new extensions. Or do you think we can merge this PR and add tests later?

**Comment by rynecheow** [comment]
@hamtiko I think that's Ok for now. I'll start reviewing this once you mark ready.

**Pull request merged**
