### PR TITLE
 add interceptor support for both request and session && alamofire 5.…

### PR DESCRIPTION
**Pull request by hamedmohammadi**
add interceptor and request modifier support

### CODE REVIEW

**Comment by hamedmohammadi** [comment]
I pull the master branch but nothing is working can you help me what just happened :)

**Comment by rynecheow** [comment]
Hi @hamedmohammadi, do rebase your branch with `master` again as it seems that the branches history seems diverged.

**Comment by rynecheow** [comment]
Please rebase the branch and reopen the pull request once the conflicts are resolved - thanks!

**Comment by hamedmohammadi** [comment]
ok I will do it soon

**Pull request closed without merging**
