### PR TITLE
Fix Swift package manager

### PR DESCRIPTION
**Pull request by rynecheow**

### CODE REVIEW

**Comment by svyatogor** [comment]
Please merge it.

**Comment by freak4pc** [comment]
Sorry for the delay in getting to this. @rynecheow can you please add a `swift test` stage to `.circleci/config.yml` (CI) ?

**Comment by rynecheow** [comment]
@sunshinejr I am not sure - it seems intermittent. Once re-run it works.

**Comment by sunshinejr** [comment]
@rynecheow ah alright. Then it seems good to go! 🚀 @freak4pc I'm gonna merge this one but in case you have additional comments we can of course get back to it asap.

also @rynecheow would you please make a new release with SPM support? 🙏

**Pull request merged**
