### PR TITLE
Version update to 4.4.0

### PR DESCRIPTION
**Pull request by rynecheow**

### CODE REVIEW

**Comment by freak4pc** [comment]
Seems the same test from before is failing on Swift 5. Can you look? If it's flaky maybe we should remove it or understand why. @rynecheow

**Comment by rynecheow** [comment]
@freak4pc We should look at it as a separate issue could we? As the test cases fail for either Swift 4.2 or Swift 5 - I'll separately raise an issue

**Comment by rynecheow** [comment]
@freak4pc Can we release this version meanwhile?

**Comment by freak4pc** [comment]
Sorry, was preoccupied with some work. Releasing now :) 
Let me know if you could look at that flaky test :] 

Thank you!

**Pull request merged**
