### PR TITLE
Update RxSwift to beta.2

### PR DESCRIPTION
**Pull request by moogle19**

### CODE REVIEW

**Comment by moogle19** [comment]
Sorry, duplicate.

**Comment by kzaher** [comment]
Hi @moogle19 ,

sorry, this was dupe :) Thnx for helping out, but can't merge 2 of them :)

**Comment by moogle19** [comment]
Hi @kzaher ,
yeah I saw that too, but #52 forgot to update the Cartfile (still at beta1).
Would be nice if you would update it, so carthage builds will work as well.

**Comment by kzaher** [comment]
Hi @moogle19 ,

oh, I'll need to update Cartfile also, forgot about that.

**Pull request closed without merging**
