### PR TITLE
[WIP] Make RxAlamofire compile on Swift 3.0

### PR DESCRIPTION
**Pull request by sergdort**
Hi, guys. I've made some changes towards Swift 3.0. #37 
Please review :)

Haven't made changes to tests though

### CODE REVIEW

**Comment by mendesbarreto** [comment]
Hello every body,

How is the situation about the merge of this pull request? 

Abs.

**Comment by orta** [comment]
It's be great to have the [travis.yml](https://github.com/RxSwiftCommunity/RxAlamofire/blob/develop/.travis.yml#L1) moved to the latest Xcode beta to give those tests a run

**Comment by kzaher** [comment]
Wow @sergdort you rule :),

I've missed this one :)

**Comment by kzaher** [comment]
Yeah, all looks good to me.

I think we can also include this one https://github.com/RxSwiftCommunity/RxAlamofire/pull/33

if it fixes temporarily Carthage integration.

I think that because of Carthage we'll need to only leave one project in root that Carthage can build and move other projects into some subdirectory or use some name hack so carthage doesn't catch them first.

**Comment by sergdort** [comment]
Hi, guys currently have an issue with running tests locally :(

The following error pops up:

`ld: framework not found Pods_RxAlamofireExample_RxAlamofireTests
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

it would be great if some one would help with this :)

**Comment by sergdort** [comment]
Hm, have no clue why its failing on pod install, all though travis uses `Cocoapods 1.1.0.beta.1`
Well now thanks to @mendesbarreto the tests are passing on my local machine

**Comment by mendesbarreto** [comment]
Hi Everybody! How it's going? 

Someone saw what happening with Travis? have any clue?

thx

**Comment by Soulflayer** [comment]
Hey guys! I am looking at migrating to RxSwift that works with Swift 3.0 and currently RxAlamofire is blocking me from updating. Any ETA on when this might be ready? 

Thanks

**Comment by sergdort** [comment]
Hi, guys, sorry for a delay. 
I've finished transition to Alamofire 4.0. Gonna push my changes today and hopefully fixe the problems with Travis

**Comment by sergdort** [comment]
The build is green 🎉🎊

**Pull request merged**
